version: '3'

networks:
  todoapp:

services:

  # nginx
  todoapp-nginx-service:
    image: nginx:stable-alpine
    container_name: todoapp-nginx-container
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/project
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - todoapp-php74-service
      - todoapp-mariadb-service
    networks:
      - todoapp

  # php
  todoapp-php74-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todoapp-php74-container
    ports:
      - "9001:9000"
    volumes:
      - .:/var/www/project
    networks:
      - todoapp
    links:
      - todoapp-mariadb-service

  # mysql
  todoapp-mariadb-service:
    image: mariadb:10
    container_name: todoapp-mariadb10-container
    ports:
      - "5306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: todoapp
    networks:
      - todoapp

  # node
  todoapp-node-service:
    image: node:latest
    container_name: todoapp-node-container
    volumes:
      - .:/var/www/project
    working_dir: /var/www/project
    networks:
      - todoapp