# Index
index:
  path: /
  controller: ToDoApp\Controller\IndexController::indexAction

# Task
create_task:
  path: /tasks
  controller: ToDoApp\Controller\TaskController::createAction
  methods: POST
update_task:
  path: /tasks/{id}
  controller: ToDoApp\Controller\TaskController::updateAction
  methods: PUT
complete_task:
  path: /tasks/{id}/complete
  controller: ToDoApp\Controller\TaskController::completeAction
  methods: POST
delete_task:
  path: /tasks/{id}
  controller: ToDoApp\Controller\TaskController::deleteAction
  methods: DELETE
get_all_tasks:
  path: /tasks
  controller: ToDoApp\Controller\TaskController::getAllAction
  methods: GET

# Cache
cache_getCacheItem:
  path: /cache/{key}/get
  controller: ToDoApp\Controller\CacheController::getAction
  methods: GET
cache_setCacheItem:
  path: /cache/{key}/set
  controller: ToDoApp\Controller\CacheController::setAction
  methods: PUT
cache_deletCacheItem:
  path: /cache/{key}/delete
  controller: ToDoApp\Controller\CacheController::deleteAction
  methods: DELETE
